name: Exercicio2Workflow

on:
  push:
    branches: [ main ]
    
env:
  NAME_FILE: OutputFile
  
jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: ${{env.NAME_FILE}}
        path: .
        if-no-files-found: error
